name: TwoArmLift
environment: robosuite

task_name: &task_name TwoArmLift

use_abs_action: &use_abs_action false
 

feedback_threshold: 0.2  # for abs, should be 0.05

dim_a: &dim_a 14
dim_o: &dim_o 48 # dim of observation for low-dim states
e: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]  # only define diagional 
loss_weight_inverse_e: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


camera_names:
  - robot0_eye_in_hand
  - robot1_eye_in_hand
  - agentview

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    agentview_image:
      shape: [3, 84, 84]
      type: rgb
    robot0_eye_in_hand_image:
      shape: [3, 84, 84]
      type: rgb
    robot0_eef_pos:
      shape: [3]
      # type default: low_dim
    robot0_eef_quat:
      shape: [4]
    robot0_gripper_qpos:
      shape: [2]
    robot1_eye_in_hand_image:
      shape: [3, 84, 84]
      type: rgb
    robot1_eef_pos:
      shape: [3]
      # type default: low_dim
    robot1_eef_quat:
      shape: [4]
    robot1_gripper_qpos:
      shape: [2]
  action: 
    shape: [14]

crop_shape: [72, 72] # used in obs_encoder

action_max_r0: [1, 1, 1]  # limits for the velocity command of the eef position
action_min_r0: [-1, -1, -1] 
action_max_r1: [1, 1, 1]
action_min_r1: [-1, -1, -1]
gripper_qpose_max: [ 0.04187732, -0.00039201]
gripper_qpose_min: [-0.00132913, -0.04164233]
robot0_eef_pos_max: [0.1622307603291485, 0.0544669567517213, 1.051553768845939]
robot0_eef_pos_min: [-0.15943653533310637, -0.23956746663405254, 0.8398654473352368]
robot1_eef_pos_max: [0.16475334207051817, 0.24165862824332227, 1.0472545850402981]
robot1_eef_pos_min: [-0.17029093508428447, -0.04304125660377853, 0.8445720751097924]

number_of_repetitions: 50
evaluations_per_training: 10
max_num_of_episodes: 162
max_time_steps_episode: 500
max_time_steps_per_repetition: 700000
